import type { Metadata } from "next";
import "./globals.css";
import './font/font_ko.css';
import './font/font_en.css';

export const metadata: Metadata = {
  title: "프레시아위키!!!!!!!!!!!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}
